/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "GenesissAI": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "GenesissAPITable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "GenesissBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "GenesissPublicBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "GenesissVectorDB": {
      "putFunction": string
      "queryFunction": string
      "removeFunction": string
      "type": "sst.aws.Vector"
    }
    "InternalAPIKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "JinaApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Judge0APIKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RTRoleArn": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ReplicateAPIKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
